config/routes.rb
Rails.application.routes.draw do
  resources :pages, only: :show

  mount Optimadmin::Engine => '/admin'

  resources :departments, only: :show, path: 'department'
  resources :services, only: :show do
    member do
      get 'team_member_search', path: 'team-member-search'
    end
  end
  resources :audiences, only: :show

  if Rails.env.test?
    resources :articles, only: [:index, :show]
    resources :article_categories, only: [:index, :show], path: 'article-category'

    resources :case_studies, only: :show, path: 'case-study'
    resources :case_study_categories, only: :show, path: 'case-study-category'

    resources :events, only: :show
    resources :event_categories, only: :show, path: 'event-category'
    resources :event_locations, only: :show, path: 'event-location'

    resources :downloads, only: :show
    # resources :download_categories, only: [:index, :show]

    resources :videos, only: :show
    resources :video_categories, only: :show, path: 'video-category'

    resources :team_members, only: [:index, :show], path: 'team-members'
    resources :offices
    resources :office_locations, only: :show, path: 'office-locations'
  end

  root to: "application#index"
end

Optimadmin::Engine.routes.draw do
  resources :download_categories, except: [:show] do
    collection do
      post 'order'
    end
    member do
      get 'toggle'
    end
  end
  resources :frequently_asked_questions, except: [:show] do
    collection do
      post 'order'
    end
    member do
      get 'toggle'
    end
  end
  resources :tour_entries, except: [:show] do
    collection do
      post 'order'
    end
    member do
      get 'toggle'
    end
  end
  resources :additional_contents, except: [:show] do
    collection do
      post 'order'
    end
    member do
      get 'toggle'
    end
  end
  resources :case_studies, except: :show do
    collection do
      post 'order'
    end
    member do
      get 'toggle'
      get 'edit_images'
      post 'update_image_default'
      post 'update_image_fill'
      post 'update_image_fit'
    end
  end


  resources :pages, except: :show do
    collection do
      post 'order'
    end
    member do
      get 'toggle'
      get 'edit_images'
      post 'update_image_default'
      post 'update_image_fill'
      post 'update_image_fit'
    end
  end
  resources :case_study_categories, except: [:show] do
    collection do
      post 'order'
    end
    member do
      get 'toggle'
    end
  end
  resources :downloads, except: [:show] do
    collection do
      post 'order'
    end
    member do
      get 'toggle'
      get 'edit_images'
      post 'update_image_default'
      post 'update_image_fill'
      post 'update_image_fit'
    end
  end

  resources :video_categories, except: [:show] do
    collection do
      post 'order'
    end
    member do
      get 'toggle'
    end
  end
  resources :videos, except: [:show] do
    collection do
      post 'order'
    end
    member do
      get 'toggle'
      get 'edit_images'
      post 'update_image_default'
      post 'update_image_fill'
      post 'update_image_fit'
    end
  end
  resources :event_locations, except: [:show] do
    collection do
      post 'order'
    end
    member do
      get 'toggle'
    end
  end
  resources :event_categories, except: [:show] do
    collection do
      post 'order'
    end
    member do
      get 'toggle'
    end
  end
  resources :events, except: [:show] do
    collection do
      post 'order'
    end
    member do
      get 'toggle'
      get 'edit_images'
      post 'update_image_default'
      post 'update_image_fill'
      post 'update_image_fit'
    end
  end
  resources :office_locations, except: [:show] do
    collection do
      post 'order'
    end
    member do
      get 'toggle'
    end
  end
  resources :business_partners, except: [:show] do
    collection do
      post 'order'
    end
    member do
      get 'toggle'
      get 'edit_images'
      post 'update_image_default'
      post 'update_image_fill'
      post 'update_image_fit'
    end
  end
  resources :awards, except: [:show] do
    collection do
      post 'order'
    end
    member do
      get 'toggle'
      get 'edit_images'
      post 'update_image_default'
      post 'update_image_fill'
      post 'update_image_fit'
    end
  end
  resources :article_categories, except: [:show] do
    collection do
      post 'order'
    end
    member do
      get 'toggle'
    end
  end
  resources :offices, except: [:show] do
    collection do
      post 'order'
    end
    member do
      get 'toggle'
      get 'edit_images'
      post 'update_image_default'
      post 'update_image_fill'
      post 'update_image_fit'
    end
  end
  resources :team_member_roles, except: [:show] do
    collection do
      post 'order'
    end
    member do
      get 'toggle'
    end
  end
  resources :team_members, except: [:show] do
    collection do
      post 'order'
    end
    member do
      get 'toggle'
      get 'edit_images'
      post 'update_image_default'
      post 'update_image_fill'
      post 'update_image_fit'
    end
  end
  resources :testimonials, except: [:show] do
    collection do
      post 'order'
    end
    member do
      get 'toggle'
    end
  end
  resources :articles, except: [:show] do
    collection do
      post 'order'
    end
    member do
      get 'toggle'
      get 'edit_images'
      post 'update_image_default'
      post 'update_image_fill'
      post 'update_image_fit'
    end
  end

  resources :departments, except: [:show] do
    collection do
      post 'order'
    end
    member do
      get 'toggle'
      get 'edit_images'
      post 'update_image_default'
      post 'update_image_fill'
      post 'update_image_fit'
    end
  end
  resources :services, except: [:show] do
    resources :related_services, only: [:index, :destroy]
    collection do
      post 'order'
    end
    member do
      get 'toggle'
      get 'edit_images'
      post 'update_image_default'
      post 'update_image_fill'
      post 'update_image_fit'
    end
  end
  resources :audiences, except: [:show] do
    collection do
      post 'order'
    end
    member do
      get 'toggle'
      get 'edit_images'
      post 'update_image_default'
      post 'update_image_fill'
      post 'update_image_fit'
    end
  end
end

app/models/office.rb
class Office < ActiveRecord::Base
  extend FriendlyId
  friendly_id :slug_candidates, use: [:slugged, :history]

  mount_uploader :image, OfficeUploader

  belongs_to :office_location
  has_many :service_offices, dependent: :destroy
  has_many :services, through: :service_offices
  has_many :team_member_offices, dependent: :destroy
  has_many :team_members, through: :team_member_offices

  delegate :name, to: :office_location, prefix: true

  validates :name, presence: true, uniqueness: { scope: :office_location_id }
  validates :postcode, presence: true
  validates :office_location, presence: true
  validates :suggested_url, uniqueness: true, allow_blank: true, case_sensitive: false

  scope :displayed, -> { joins(:office_location).where(display: true).merge(OfficeLocation.displayed) }

  def slug_candidates
    [
      :suggested_url,
      :name,
      [:suggested_url, :name]
    ]
  end

  def should_generate_new_friendly_id?
    slug.blank? || suggested_url_changed? || name_changed?
  end
end

app/models/office/location.rb
class Office::Location < ActiveRecord::Base

  extend FriendlyId
  friendly_id :slug_candidates, use: [:slugged, :history]

  has_many :offices, foreign_key: :office_location_id, dependent: :destroy

  validates :name, presence: true, uniqueness: true

  def slug_candidates
    [
      :suggested_url,
      :name,
      [:suggested_url, :name]
    ]
  end

  def should_generate_new_friendly_id?
    slug.blank? || suggested_url_changed? || name_changed?
  end
end

app/models/service/office.rb
class Service::Office < ActiveRecord::Base
  belongs_to :service
  belongs_to :office
end

app/controllers/offices_controller.rb
class OfficesController < ApplicationController
  def show
  end
end

app/controllers/optimadmin/additional_contents_controller.rb
module Optimadmin
  class AdditionalContentsController < Optimadmin::ApplicationController
    before_action :set_additional_content, only: [:show, :edit, :update, :destroy]

    def index
      @additional_contents = Optimadmin::BaseCollectionPresenter.new(collection: AdditionalContent.where('title ILIKE ?', "%#{params[:search]}%").page(params[:page]).per(params[:per_page] || 15), view_template: view_context, presenter: Optimadmin::AdditionalContentPresenter)
    end

    def show
    end

    def new
      @additional_content = AdditionalContent.new
    end

    def edit
    end

    def create
      @additional_content = AdditionalContent.new(additional_content_params)
      if @additional_content.save
        redirect_to additional_contents_url, notice: 'Additional content was successfully created.'
      else
        render :new
      end
    end

    def update
      if @additional_content.update(additional_content_params)
        redirect_to additional_contents_url, notice: 'Additional content was successfully updated.'
      else
        render :edit
      end
    end

    def destroy
      @additional_content.destroy
      redirect_to additional_contents_url, notice: 'Additional content was successfully destroyed.'
    end

  private


    def set_additional_content
      @additional_content = AdditionalContent.find(params[:id])
    end

    def additional_content_params
      params.require(:additional_content).permit(:area, :title, :content, :display)
    end
  end
end

app/controllers/optimadmin/article_categories_controller.rb
module Optimadmin
  class ArticleCategoriesController < Optimadmin::ApplicationController
    before_action :set_article_category, only: [:show, :edit, :update, :destroy]

    def index
      @article_categories = Optimadmin::BaseCollectionPresenter.new(collection: ArticleCategory.where('name ILIKE ?', "%#{params[:search]}%").page(params[:page]).per(params[:per_page] || 15), view_template: view_context, presenter: Optimadmin::ArticleCategoryPresenter)
    end

    def show
    end

    def new
      @article_category = ArticleCategory.new
    end

    def edit
    end

    def create
      @article_category = ArticleCategory.new(article_category_params)
      if @article_category.save
        redirect_to article_categories_url, notice: 'Article category was successfully created.'
      else
        render :new
      end
    end

    def update
      if @article_category.update(article_category_params)
        redirect_to article_categories_url, notice: 'Article category was successfully updated.'
      else
        render :edit
      end
    end

    def destroy
      @article_category.destroy
      redirect_to article_categories_url, notice: 'Article category was successfully destroyed.'
    end

  private


    def set_article_category
      @article_category = ArticleCategory.find(params[:id])
    end

    def article_category_params
      params.require(:article_category).permit(:name, :suggested_url)
    end
  end
end

app/controllers/optimadmin/articles_controller.rb
module Optimadmin
  class ArticlesController < Optimadmin::ApplicationController
    before_action :set_article, only: [:show, :edit, :update, :destroy]

    edit_images_for Article, [[:image, { index: ['fill', 316, 164], show: ['fill', 165, 135], activity_stream: ['fill', 199, 155] }]]

    def index
      @articles = Optimadmin::BaseCollectionPresenter.new(collection: Article.where('title ILIKE ?', "%#{params[:search]}%").page(params[:page]).per(params[:per_page] || 15).order(date: :desc), view_template: view_context, presenter: Optimadmin::ArticlePresenter)
    end

    def show
    end

    def new
      @article = Article.new
    end

    def edit
    end

    def create
      @article = Article.new(article_params)
      if @article.save
        redirect_to articles_url, notice: 'Article was successfully created.'
      else
        render :new
      end
    end

    def update
      if @article.update(article_params)
        redirect_to articles_url, notice: 'Article was successfully updated.'
      else
        render :edit
      end
    end

    def destroy
      @article.destroy
      redirect_to articles_url, notice: 'Article was successfully destroyed.'
    end

  private


    def set_article
      @article = Article.find(params[:id])
    end

    def article_params
      params.require(:article).permit(:title, :summary, :image, :content, :date, :slug, :suggested_url, :display,
                                      :team_member_id, :article_category_id, :home_page_highlight, service_ids: [])
    end
  end
end

app/controllers/optimadmin/audiences_controller.rb
module Optimadmin
  class AudiencesController < Optimadmin::ApplicationController
    before_action :set_audience, only: [:show, :edit, :update, :destroy]

    def index
      @audiences = Optimadmin::BaseCollectionPresenter.new(collection: Audience.positioned.where('name LIKE ?', "%#{params[:search]}%").page(params[:page]).per(params[:per_page] || 15), view_template: view_context, presenter: Optimadmin::AudiencePresenter)
    end

    def show
    end

    def new
      @audience = Audience.new
    end

    def edit
    end

    def create
      @audience = Audience.new(audience_params)
      if @audience.save
        redirect_to audiences_url, notice: 'Audience was successfully created.'
      else
        render :new
      end
    end

    def update
      if @audience.update(audience_params)
        redirect_to audiences_url, notice: 'Audience was successfully updated.'
      else
        render :edit
      end
    end

    def destroy
      @audience.destroy
      redirect_to audiences_url, notice: 'Audience was successfully destroyed.'
    end

  private


    def set_audience
      @audience = Audience.friendly.find(params[:id])
    end

    def audience_params
      params.require(:audience).permit(:name, :colour, :sub_heading, :image, :remote_image_url, :image_cache, :summary, :content, :layout, :display, :suggested_url)
    end
  end
end

app/controllers/optimadmin/awards_controller.rb
module Optimadmin
  class AwardsController < Optimadmin::ApplicationController
    before_action :set_award, only: [:show, :edit, :update, :destroy]

    edit_images_for Award, [[:image, { show: ['fit', 150, 80] }]]

    def index
      @awards = Optimadmin::BaseCollectionPresenter.new(collection: Award.positioned.where('name ILIKE ?', "%#{params[:search]}%").page(params[:page]).per(params[:per_page] || 15), view_template: view_context, presenter: Optimadmin::AwardPresenter)
    end

    def show
    end

    def new
      @award = Award.new
    end

    def edit
    end

    def create
      @award = Award.new(award_params)
      if @award.save
        redirect_to awards_url, notice: 'Award was successfully created.'
      else
        render :new
      end
    end

    def update
      if @award.update(award_params)
        redirect_to awards_url, notice: 'Award was successfully updated.'
      else
        render :edit
      end
    end

    def destroy
      @award.destroy
      redirect_to awards_url, notice: 'Award was successfully destroyed.'
    end

  private


    def set_award
      @award = Award.find(params[:id])
    end

    def award_params
      params.require(:award).permit(:position, :name, :link, :image, :award_type, :display, :in_footer, service_ids: [])
    end
  end
end

app/controllers/optimadmin/business_partners_controller.rb
module Optimadmin
  class BusinessPartnersController < Optimadmin::ApplicationController
    before_action :set_business_partner, only: [:show, :edit, :update, :destroy]

    edit_images_for BusinessPartner, [[:image, { show: ['fit', 188, 98] }]]

    def index
      @business_partners = Optimadmin::BaseCollectionPresenter.new(collection: BusinessPartner.positioned.where('name ILIKE ?', "%#{params[:search]}%").page(params[:page]).per(params[:per_page] || 15), view_template: view_context, presenter: Optimadmin::BusinessPartnerPresenter)
    end

    def show
    end

    def new
      @business_partner = BusinessPartner.new
    end

    def edit
    end

    def create
      @business_partner = BusinessPartner.new(business_partner_params)
      if @business_partner.save
        redirect_to business_partners_url, notice: 'Business partner was successfully created.'
      else
        render :new
      end
    end

    def update
      if @business_partner.update(business_partner_params)
        redirect_to business_partners_url, notice: 'Business partner was successfully updated.'
      else
        render :edit
      end
    end

    def destroy
      @business_partner.destroy
      redirect_to business_partners_url, notice: 'Business partner was successfully destroyed.'
    end

  private


    def set_business_partner
      @business_partner = BusinessPartner.find(params[:id])
    end

    def business_partner_params
      params.require(:business_partner).permit(:position, :name, :link, :image, :display)
    end
  end
end

app/views/optimadmin/offices/_form.html.erb
<%= form_for(office) do |f| %>
<% if office.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(office.errors.count, "error") %> prohibited this office from being saved:</h2>

    <ul>
      <% office.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>



  <div class="tabs prevent-flash">
    <ul class="tab-list">
      <li><a href="#tabs-1">Content</a></li>
      <li><a href="#tabs-2">Media</a></li>
      <li><a href="#tabs-3">Settings</a></li>
      <li>
        <%= link_to '#', class: 'destroy-tabs right', data: { class: 'tabs' } do %>
          <%= octicon('chevron-down') %>
        <% end %>
      </li>
    </ul>

    <%= field_set_tag nil, id: 'tabs-1' do %>
            <div class="field">
        <%= f.label :name %><br>
        <%= f.text_field :name %>
      </div>
            <div class="field">
        <%= f.label :building_name %><br>
        <%= f.text_field :building_name %>
      </div>
            <div class="field">
        <%= f.label :building_number %><br>
        <%= f.text_field :building_number %>
      </div>
            <div class="field">
        <%= f.label :street %><br>
        <%= f.text_field :street %>
      </div>
            <div class="field">
        <%= f.label :town %><br>
        <%= f.text_field :town %>
      </div>
            <div class="field">
        <%= f.label :county %><br>
        <%= f.text_field :county %>
      </div>
            <div class="field">
        <%= f.label :postcode %><br>
        <%= f.text_field :postcode %>
      </div>
            <div class="field">
        <%= f.label :phone_number %><br>
        <%= f.text_field :phone_number %>
      </div>
            <div class="field">
        <%= f.label :fax_number %><br>
        <%= f.text_field :fax_number %>
      </div>
            <div class="field">
        <%= f.label :email %><br>
        <%= f.text_field :email %>
      </div>
            <div class="field">
        <%= f.label :dx_number %><br>
        <%= f.text_field :dx_number %>
      </div>
            <div class="field">
        <%= f.label :details %><br>
        <%= f.text_area :details, class: 'tinymce' %>
      </div>
            <div class="field">
        <%= f.label :office_location_id %><br>
        <%= f.select :office_location_id, OfficeLocation.pluck(:name, :id), prompt: 'Please select' %>
      </div>
          <% end %>

    <%= field_set_tag nil, id: 'tabs-2' do %>
            <%= f.image_field :image %>

          <% end %>

    <%= field_set_tag nil, id: 'tabs-3' do %>
    <div class="field">
<%= f.label :team_member_ids, "Team Members" %><br>
<%= f.select :team_member_ids, TeamMember.all.map{|x| ["#{x.forename} #{x.surname}", x.id]}, {  }, { multiple: true, class: 'multiple-select' } %>
</div>
    <div class="field">
<%= f.label :service_ids, "Services" %><br>
<%= f.select :service_ids, grouped_options_for_select(Service.includes(:department).group_by(&:department).map{|x| ["#{x[0].name}", x[1].map{|y| [y.name, y.id]}]}, selected: f.object.services.pluck(:id)), {  }, { multiple: true, class: 'multiple-select' } %>
</div>
            <div class="field">
              <div class="field">
                <%= f.label :suggested_url %> <%= render 'optimadmin/shared/suggested_url_field' %><br>
                <%= f.text_field :suggested_url %>
              </div>
        <%= f.label :display %><br>
        <%= f.check_box :display %>
      </div>
          <% end %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/optimadmin/offices/_office.html.erb
<div class="row collapse module-list-index <%= cycle('odd', 'even') %>" data-equalizer="module-list" id="item_<%= office_presenter.id %>">
  

  
    <div class="large-6 small-8 columns" data-equalizer-watch="module-list">
  
    <%= office_presenter.toggle_title %>
  </div>

  
    <div class="large-2 hide-for-medium-down columns" data-equalizer-watch="module-list">
      <%= office_presenter.edit_image(:image)%>
    </div>
  

  <div class="large-1 small-4 columns" data-equalizer-watch="module-list">
    <%= office_presenter.toggle_link %>
  </div>

  <div class="large-1 small-4 columns" data-equalizer-watch="module-list">
    <%= office_presenter.view_link %>
  </div>

  <div class="large-1 small-4 columns" data-equalizer-watch="module-list">
    <%= office_presenter.edit_link %>
  </div>

  <div class="large-1 hide-for-medium-down columns last" data-equalizer-watch="module-list">
    <%= office_presenter.delete_link %>
  </div>

  <div class="row module-list-detail hide" id="index-list-<%= office_presenter.id %>">
    <div class="small-12 columns module-list-summary last">
      <%= office_presenter.optimadmin_summary %>
    </div>
  </div>
</div>

app/views/optimadmin/offices/edit.html.erb
<%= render 'optimadmin/shared/header/main_title', title: 'Edit Office' %>

<div class="main-content">
  <%= render 'optimadmin/shared/module/form/back', path: offices_path, title: 'Office' %>

  <%= render 'form', office: @office %>
</div>

app/views/optimadmin/offices/index.html.erb
<%= render 'optimadmin/shared/header/main_title', title: 'Manage Offices' %>

<div class="main-content">
  <div class="row module-header collapse">
    <%= render 'optimadmin/shared/module/index/new_item', title: 'Office', object: Office, path: new_office_path %>
    <%= render 'optimadmin/shared/search_form' %>
    <%= render 'optimadmin/shared/module/index/pagination' %>
    <!--
      <%= render 'optimadmin/shared/module/index/order', options: [['Username', 'username']] %>
    -->
    <%= render 'optimadmin/shared/module/index/recycle_bin', items: @offices.size, path: root_url %>
  </div>

  <div class="row collapse module-list-index header">
    

    

    
      <%= list_item 'large-6 small-8' do %>
        <%= link_to octicon('chevron-down'), '#', class: 'helper-link index-list-expand-all', data: { this_class: 'octicon-chevron-up octicon-chevron-down' } %>
        Title
      <% end %>
    

    
    <%= list_item 'large-2 hide-for-medium-down' do 'Image' end %>
    

    <%= list_item { 'Display' } %>
    <%= list_item { 'View' } %>
    <%= list_item { 'Edit' } %>

    <%= list_item 'large-1 hide-for-medium-down text-center last' do 'Delete' end %>
  </div>

  <!-- <div class='module-sortable' data-module="Office"> -->
  <%= render partial: 'office', collection: @offices, as: :office_presenter %>
  <!-- </div> -->
  <%= paginate @offices %>
</div>

app/views/optimadmin/offices/new.html.erb
<%= render 'optimadmin/shared/header/main_title', title: 'New Office' %>

<div class="main-content">
  <%= render 'optimadmin/shared/module/form/back', path: offices_path, title: 'Office' %>

  <%= render 'form', office: @office %>
</div>